package ejercicio.pedidosva;

import java.awt.Image;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

public class FormAgregarAlCarrito extends javax.swing.JFrame {

    private FormMenuPrincipal formMenuPrincipal;
    private Carrito carrito;
    private int cantidadCombo = 1;

    public void actualizarCombo(String nombre, double precio, String descripcion, String imagenPath) {
        lblNombreCombo.setText(nombre);
        lblDescripcionCombo.setText(descripcion); // Actualiza la descripción
        lblPrecioCombo.setText("$" + precio); // Actualiza el precio

        // Intentar cargar la imagen
        try {
            File imagenFile = new File(imagenPath);
            if (imagenFile.exists()) {
                Image imagen = ImageIO.read(imagenFile);
                ImageIcon icon = new ImageIcon(imagen);
                lblImagenCombo.setIcon(icon);
            } else {
                // Mostrar un mensaje de error si la imagen no se encuentra
                lblImagenCombo.setText("Imagen no encontrada");
            }
        } catch (IOException e) {
            // Capturar y manejar cualquier excepción de E/S
            e.printStackTrace();
            lblImagenCombo.setText("Error al cargar la imagen");
        }
    }

    // Método para incrementar la cantidad del combo
    private void incrementarCantidad() {
        cantidadCombo++;
        lblCantidad.setText(Integer.toString(cantidadCombo));
    }

    // Método para decrementar la cantidad del combo
    private void decrementarCantidad() {
        if (cantidadCombo > 1) {
            cantidadCombo--;
            lblCantidad.setText(Integer.toString(cantidadCombo));
        }
    }

    public FormAgregarAlCarrito(FormMenuPrincipal formMenuPrincipal, Carrito carrito) {
        this.formMenuPrincipal = formMenuPrincipal;
        this.carrito = carrito;
        
        this.setUndecorated(true); // Establecer undecorated a true
        initComponents();
        
    }

    public void setFormMenuPrincipal(FormMenuPrincipal formMenuPrincipal, Carrito carrito) {
        this.formMenuPrincipal = formMenuPrincipal;
        this.setLocationRelativeTo(null); // Centrar en la pantalla
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblDescripcionCombo = new javax.swing.JLabel();
        lblImagenCombo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnIncrementar = new javax.swing.JButton();
        btnDecrementar = new javax.swing.JButton();
        lblCantidad = new javax.swing.JLabel();
        lblNombreCombo = new javax.swing.JLabel();
        lblPrecioCombo = new javax.swing.JLabel();
        btnRegresarMenuPrincipal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDescripcionCombo.setBackground(new java.awt.Color(0, 0, 0));
        lblDescripcionCombo.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        lblDescripcionCombo.setForeground(new java.awt.Color(0, 0, 0));
        lblDescripcionCombo.setText("Aqui se vera la descripción");
        lblDescripcionCombo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(lblDescripcionCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 200, 40));

        lblImagenCombo.setForeground(new java.awt.Color(0, 0, 0));
        lblImagenCombo.setText("imagen Combo");
        jPanel2.add(lblImagenCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 250, 140));

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton1.setText("Agregar a pedido");
        jButton1.setFocusable(false);
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 150, 70));

        btnIncrementar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnIncrementar.setText("+");
        btnIncrementar.setFocusable(false);
        btnIncrementar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncrementarActionPerformed(evt);
            }
        });
        jPanel2.add(btnIncrementar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 70, 50));

        btnDecrementar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnDecrementar.setText("-");
        btnDecrementar.setFocusable(false);
        btnDecrementar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecrementarActionPerformed(evt);
            }
        });
        jPanel2.add(btnDecrementar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 70, 50));

        lblCantidad.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblCantidad.setForeground(new java.awt.Color(0, 0, 0));
        lblCantidad.setText("1");
        jPanel2.add(lblCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 20, -1));

        lblNombreCombo.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        lblNombreCombo.setForeground(new java.awt.Color(0, 0, 0));
        lblNombreCombo.setText("jLabel1");
        jPanel2.add(lblNombreCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 70));

        lblPrecioCombo.setBackground(new java.awt.Color(255, 0, 0));
        lblPrecioCombo.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        lblPrecioCombo.setForeground(new java.awt.Color(255, 0, 51));
        lblPrecioCombo.setText("precio");
        jPanel2.add(lblPrecioCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 160, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 470, 300));

        btnRegresarMenuPrincipal.setBackground(new java.awt.Color(0, 0, 0));
        btnRegresarMenuPrincipal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRegresarMenuPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresarMenuPrincipal.setText("SALIR");
        btnRegresarMenuPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresarMenuPrincipal.setFocusable(false);
        btnRegresarMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarMenuPrincipalActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresarMenuPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 140, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIncrementarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncrementarActionPerformed
        incrementarCantidad();
    }//GEN-LAST:event_btnIncrementarActionPerformed

    private void btnDecrementarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecrementarActionPerformed
        decrementarCantidad();
    }//GEN-LAST:event_btnDecrementarActionPerformed

    private void btnRegresarMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarMenuPrincipalActionPerformed
        

        // Volver a activar el formulario principal
        formMenuPrincipal.setEnabled(true);
    // Cerrar el formulario actual
        this.dispose();
    }//GEN-LAST:event_btnRegresarMenuPrincipalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDecrementar;
    private javax.swing.JButton btnIncrementar;
    private javax.swing.JButton btnRegresarMenuPrincipal;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblDescripcionCombo;
    private javax.swing.JLabel lblImagenCombo;
    private javax.swing.JLabel lblNombreCombo;
    private javax.swing.JLabel lblPrecioCombo;
    // End of variables declaration//GEN-END:variables
}
